/**
 * ============================================================
 * WHICH PERMISSION EACH API ROUTE NEEDS
 * ============================================================
 * One table per router, used by middleware/permissionGuard.js
 * (router.use(guard(ROUTE_PERMISSIONS.quotes))). Paths are relative to
 * the router's mount point; the first matching line wins, so literal
 * paths come before "/:id". `null` = no extra permission: self-service,
 * manager approvals, or a rule that depends on the record / the body
 * (checked in the handler, e.g. the target status of a delivery note).
 *
 * routes/permissionGuard.coverage.test.js fails if a route exists
 * without a line here.
 * ============================================================
 */
const translations = (editKey) => [
  ["GET /:id/translations", null],
  ["PUT /:id/translations/:field/:lang", editKey],
  ["POST /:id/translations/:field/:lang/regenerate", editKey],
];

const ROUTE_PERMISSIONS = {
  // ---------------------------------------------------------------- HR
  employees: [
    ["GET /export", "hr.employees.export"],
    ["POST /bulk-import/preview", "hr.employees.import"],
    ["POST /bulk-import/commit", "hr.employees.import"],
    ["GET /", "hr.employees.view"],
    ["POST /", "hr.employees.create"],
    ["GET /:id/documents/:type/pdf", "hr.employees.print"],
    ["POST /:id/photo", "hr.employees.edit"],
    ["DELETE /:id/photo", "hr.employees.edit"],
    ["POST /:id/create-login", "hr.accounts.manage"],
    ["POST /:id/reset-password", "hr.accounts.manage"],
    ["PATCH /:id/link-user", "hr.accounts.manage"],
    ["PATCH /:id/unlink-user", "hr.accounts.manage"],
    ...translations("hr.employees.edit"),
    ["GET /:id", "hr.employees.view"],
    ["PUT /:id", "hr.employees.edit"],
    ["DELETE /:id", "hr.employees.delete"],
  ],
  salaries: [
    ["GET /", "hr.salaries.view"],
    ["GET /:id", "hr.salaries.view"],
    ["POST /", "hr.salaries.create"],
    ["PUT /:id", "hr.salaries.edit"],
    ["DELETE /:id", "hr.salaries.delete"],
  ],
  absences: [
    ["GET /calendar", "hr.absences.view"],
    ["GET /", "hr.absences.view"],
    ["PATCH /:id/review", null], // HR approvers or the employee's managers — decided in the handler
    ...translations("hr.absences.edit"),
    ["GET /:id", "hr.absences.view"],
    ["POST /", "hr.absences.create"],
    ["PUT /:id", "hr.absences.edit"],
    ["DELETE /:id", "hr.absences.delete"],
  ],
  advances: [
    ["GET /", "hr.advances.view"],
    ["PATCH /:id/review", null],
    ...translations("hr.advances.edit"),
    ["GET /:id", "hr.advances.view"],
    ["POST /", "hr.advances.create"],
    ["PUT /:id", "hr.advances.edit"],
    ["DELETE /:id", "hr.advances.delete"],
  ],
  payroll: [
    ["POST /runs", "hr.payroll.run"],
    ["POST /runs/:id/regenerate", "hr.payroll.run"],
    ["GET /runs", "hr.payroll.view"],
    ["GET /runs/:id/export/:type", "hr.payroll.export"],
    ["GET /runs/:id", "hr.payroll.view"],
    ["POST /runs/:id/complete", "hr.payroll.validate"],
    ["DELETE /runs/:id", "hr.payroll.delete"],
    ["GET /payslips", "hr.payroll.view"],
    ["GET /payslips/:id/pdf", "hr.payroll.view"],
    ["PATCH /payslips/:id/mark-paid", "hr.payroll.markPaid"],
  ],
  declarations: [
    ["POST /runs/:id/damancom/preview", "hr.declarations.view"],
    ["POST /runs/:id/damancom/file", "hr.declarations.export"],
    ["GET /runs/:id/bank-transfer/file", "hr.declarations.export"],
    ["GET /runs/:id/bank-transfer", "hr.declarations.view"],
    ["GET /runs/:id/ir", "hr.declarations.view"],
    ["GET /ir-annual/file", "hr.declarations.export"],
    ["GET /ir-annual", "hr.declarations.view"],
  ],
  contracts: [
    ["GET /expiring", "hr.contracts.view"],
    ["GET /", "hr.contracts.view"],
    ["POST /", "hr.contracts.create"],
    ["POST /:id/renew", "hr.contracts.renew"],
    ...translations("hr.contracts.edit"),
    ["PUT /:id", "hr.contracts.edit"],
    ["DELETE /:id", "hr.contracts.delete"],
  ],
  documents: [
    ["GET /expiring", "hr.documents.view"],
    ["GET /", "hr.documents.view"],
    ["POST /", "hr.documents.create"],
    ...translations("hr.documents.edit"),
    ["PUT /:id", "hr.documents.edit"],
    ["DELETE /:id", "hr.documents.delete"],
  ],
  attendance: [
    ["POST /clock-in", null], // self-service
    ["POST /clock-out", null],
    ["GET /today", null],
    ["GET /summary", "hr.attendance.view"],
    ["GET /", "hr.attendance.view"],
    ...translations("hr.attendance.edit"),
    ["PUT /:id", "hr.attendance.edit"],
  ],
  leave: [
    ["GET /balances/export", "hr.leave.export"],
    ["GET /balances", "hr.leave.view"],
    ["PATCH /opening-balance/:employeeId", "hr.leave.edit"],
  ],
  holidays: [
    ["GET /template", "hr.holidays.import"],
    ["POST /import/preview", "hr.holidays.import"],
    ["POST /import/commit", "hr.holidays.import"],
    ["GET /", "hr.holidays.view"],
    ["POST /", "hr.holidays.create"],
    ["PUT /:id", "hr.holidays.edit"],
    ["DELETE /:id", "hr.holidays.delete"],
  ],
  performanceReviews: [
    ["GET /mine", null],
    ["PATCH /:id/acknowledge", null], // the reviewed employee
    ["GET /", "hr.reviews.view"],
    ["PATCH /:id/submit", "hr.reviews.submit"],
    ...translations("hr.reviews.edit"),
    ["GET /:id", "hr.reviews.view"],
    ["POST /", "hr.reviews.create"],
    ["PUT /:id", "hr.reviews.edit"],
    ["DELETE /:id", "hr.reviews.delete"],
  ],
  disciplinaryActions: [
    ["GET /mine", null],
    ["PATCH /:id/acknowledge", null],
    ["GET /", "hr.discipline.view"],
    ...translations("hr.discipline.edit"),
    ["GET /:id", "hr.discipline.view"],
    ["POST /", "hr.discipline.create"],
    ["PUT /:id", "hr.discipline.edit"],
    ["DELETE /:id", "hr.discipline.delete"],
  ],
  reports: [
    ["GET /headcount", "hr.reports.view"],
    ["GET /turnover", "hr.reports.view"],
    ["GET /absenteeism", "hr.reports.view"],
    ["GET /current-payroll-estimate", "hr.reports.view"],
    ["GET /payroll-cost", "hr.reports.view"],
    ["GET /employee-rankings", "hr.reports.view"],
  ],
  auditLogs: [
    ["GET /", "hr.auditLogs.view"],
    ["DELETE /:id", null], // admins only (handler)
  ],

  // ------------------------------------------------------ Organisation
  departments: [
    ["GET /managed", null], // "My department" (its manager)
    ["GET /", "organization.departments.view"],
    ["POST /seed-defaults", "organization.departments.create"],
    ["POST /", "organization.departments.create"],
    ...translations("organization.departments.edit"),
    ["PUT /:id", "organization.departments.edit"],
    ["DELETE /:id", "organization.departments.delete"],
  ],
  jobPositions: [
    ["GET /", "organization.positions.view"],
    ["POST /", "organization.positions.create"],
    ["PATCH /:id/access", null], // admins or the department's manager (handler)
    ...translations("organization.positions.edit"),
    ["PUT /:id", "organization.positions.edit"],
    ["DELETE /:id", "organization.positions.delete"],
  ],
  workSchedule: [
    ["GET /list", null], // read by HR / organisation too (handler)
    ["GET /", null],
    ["PUT /", "organization.schedule.edit"],
    ["POST /", "organization.schedule.edit"],
    ["PATCH /:id/default", "organization.schedule.edit"],
    ["PUT /:id/departments", "organization.schedule.edit"],
    ["PUT /:id", "organization.schedule.edit"],
    ["DELETE /:id", "organization.schedule.edit"],
  ],

  // ------------------------------------------------------------- Sales
  customers: [
    ["GET /", "sales.customers.view"],
    ["GET /:id", "sales.customers.view"],
    ["POST /", "sales.customers.create"],
    ["PUT /:id", "sales.customers.edit"],
    ["DELETE /:id", "sales.customers.delete"],
  ],
  quotes: [
    ["GET /", "sales.quotes.view"],
    ["GET /:id/pdf", "sales.quotes.view"],
    ["GET /:id", "sales.quotes.view"],
    ["POST /", "sales.quotes.create"],
    ["PUT /:id", "sales.quotes.edit"],
    ["DELETE /:id", "sales.quotes.delete"],
    ["POST /:id/duplicate", "sales.quotes.create"],
    ["PATCH /:id/status", ["sales.quotes.send", "sales.quotes.decide"]], // which one: handler (target status)
    ["POST /:id/email", "sales.quotes.send"],
    ["POST /:id/project", "sales.quotes.toProject"],
    ["POST /:id/deposit", "sales.quotes.invoice"],
    ["POST /:id/invoice", "sales.quotes.invoice"],
  ],
  salesInvoices: [
    ["GET /reports/receivables", "sales.reports.view"],
    ["GET /reports/vat", "sales.reports.view"],
    ["GET /", "sales.invoices.view"],
    ["GET /:id/pdf", "sales.invoices.view"],
    ["GET /:id", "sales.invoices.view"],
    ["POST /", "sales.invoices.create"],
    ["PUT /:id", "sales.invoices.edit"],
    ["DELETE /:id/payments/:paymentId", "sales.payments.delete"],
    ["DELETE /:id", "sales.invoices.delete"],
    ["POST /:id/issue", "sales.invoices.issue"],
    ["POST /:id/payments", "sales.payments.create"],
    ["POST /:id/credit-note", "sales.invoices.creditNote"],
    ["POST /:id/apply-credit", "sales.invoices.creditNote"],
    ["POST /:id/email", "sales.invoices.send"],
  ],

  // -------------------------------------------------------- Purchasing
  suppliers: [
    ["GET /", ["purchasing.suppliers.view", "inventory.articles.view"]],
    ["GET /:id/statement", "purchasing.suppliers.view"],
    ["GET /:id", "purchasing.suppliers.view"],
    ["POST /:id/documents", "purchasing.suppliers.documents"],
    ["DELETE /:id/documents/:docId", "purchasing.suppliers.documents"],
    ["POST /", "purchasing.suppliers.create"],
    ["PUT /:id", "purchasing.suppliers.edit"],
    ["DELETE /:id", "purchasing.suppliers.delete"],
  ],
  priceRequests: [
    ["GET /compare/:group", "purchasing.priceRequests.view"],
    ["GET /", "purchasing.priceRequests.view"],
    ["POST /:id/email", "purchasing.priceRequests.send"],
    ["GET /:id/pdf", "purchasing.priceRequests.view"],
    ["GET /:id", "purchasing.priceRequests.view"],
    ["POST /", "purchasing.priceRequests.create"],
    ["PUT /:id", "purchasing.priceRequests.edit"],
    ["POST /:id/quote-file", "purchasing.priceRequests.edit"],
    ["POST /:id/convert", "purchasing.priceRequests.convert"],
    ["DELETE /:id", "purchasing.priceRequests.delete"],
  ],
  purchaseOrders: [
    ["GET /summary", "purchasing.orders.view"],
    ["GET /reports/vat-deductions", "purchasing.reports.view"],
    ["GET /reports/accounting", "purchasing.reports.view"],
    ["GET /reports/aged-balance", "purchasing.reports.view"],
    ["GET /reports/restock", "purchasing.reports.view"],
    ["GET /invoices", "purchasing.invoices.view"],
    ["GET /by-product/:productId", "purchasing.orders.view"],
    ["POST /supplier-payments", "purchasing.payments.create"],
    ["GET /", "purchasing.orders.view"],
    ["GET /:id/pdf", "purchasing.orders.view"],
    ["GET /:id", "purchasing.orders.view"],
    ["POST /", "purchasing.orders.create"],
    ["PUT /:id", "purchasing.orders.edit"],
    ["PATCH /:id/project", "purchasing.orders.edit"],
    ["PATCH /:id/status", "purchasing.orders.send"],
    ["PATCH /:id/approve", "purchasing.orders.approve"],
    ["PATCH /:id/reject-approval", "purchasing.orders.approve"],
    ["POST /:id/email", "purchasing.orders.send"],
    ["POST /:id/receptions", "purchasing.orders.receive"],
    ["PATCH /:id/lines/:lineId/close", "purchasing.orders.receive"],
    ["PATCH /:id/lines/:lineId/reopen", "purchasing.orders.receive"],
    ["POST /:id/lines/:lineId/create-article", ["inventory.articles.create", "purchasing.orders.receive"]],
    ["POST /:id/invoices", "purchasing.invoices.create"],
    ["DELETE /:id/invoices/:invoiceId", "purchasing.invoices.delete"],
    ["POST /:id/payments", "purchasing.payments.create"],
    ["DELETE /:id/payments/:paymentId", "purchasing.payments.delete"],
    ["DELETE /:id", "purchasing.orders.delete"],
  ],
  purchaseRequests: [
    ["GET /open-count", ["inventory.requests.view", "purchasing.requests.view"]],
    ["GET /", ["inventory.requests.view", "purchasing.requests.view"]],
    ["POST /", "inventory.requests.create"],
    ["PATCH /:id/process", "purchasing.requests.process"],
    ["PATCH /:id/review", "purchasing.requests.process"],
    ...translations(["inventory.requests.create", "purchasing.requests.process"]),
    ["DELETE /:id", "inventory.requests.delete"],
  ],

  // --------------------------------------------------------- Inventory
  products: [
    ["GET /suggestions", "inventory.articles.view"],
    ["GET /", "inventory.articles.view"],
    ["GET /:id/movements", "inventory.articles.view"],
    ...translations("inventory.articles.edit"),
    ["GET /:id", "inventory.articles.view"],
    ["POST /", "inventory.articles.create"],
    ["PUT /:id", "inventory.articles.edit"],
    ["PATCH /:id/supplier-info", ["inventory.articles.edit", "purchasing.orders.edit"]],
    ["POST /:id/adjust", "inventory.articles.adjust"],
    ["POST /:id/photo", "inventory.articles.edit"],
    ["DELETE /:id", "inventory.articles.delete"],
  ],
  inventoryCategories: [
    ["GET /", ["inventory.articles.view", "inventory.categories.view"]],
    ["POST /", "inventory.categories.create"],
    ...translations("inventory.categories.edit"),
    ["PUT /:id", "inventory.categories.edit"],
    ["DELETE /:id", "inventory.categories.delete"],
  ],

  // -------------------------------------------------------- Production
  productionConfig: [
    ["GET /settings", ["production.config.view", "production.catalog.view", "production.orders.view", "projects.projects.view"]],
    ["PUT /settings", "production.config.edit"],
    ["GET /workshops", ["production.config.view", "production.orders.view", "projects.projects.view"]],
    ["POST /workshops", "production.config.edit"],
    ["PUT /workshops/:id", "production.config.edit"],
    ["DELETE /workshops/:id", "production.config.edit"],
    ["GET /finishes", ["production.config.view", "production.catalog.view", "production.orders.view", "projects.projects.view", "sales.quotes.view"]],
    ["POST /finishes", "production.config.edit"],
    ["PUT /finishes/:id", "production.config.edit"],
    ["DELETE /finishes/:id", "production.config.edit"],
    ["GET /series", ["production.catalog.view", "production.config.view", "projects.projects.view", "sales.quotes.view"]],
    ["POST /series", "production.catalog.edit"],
    ["PUT /series/:id", "production.catalog.edit"],
    ["DELETE /series/:id", "production.catalog.delete"],
    ["GET /catalog/:key", "production.catalog.view"],
    ["GET /catalog", ["production.catalog.view", "projects.projects.view", "sales.quotes.view"]],
    ["POST /models/import", "production.catalog.create"],
    ["GET /models", ["production.catalog.view", "projects.projects.view", "sales.quotes.view", "production.orders.view"]],
    ["GET /models/:id", ["production.catalog.view", "projects.projects.view", "sales.quotes.view", "production.orders.view"]],
    ["POST /models", "production.catalog.create"],
    ["PUT /models/:id", "production.catalog.edit"],
    ["POST /models/:id/duplicate", "production.catalog.create"],
    ["DELETE /models/:id", "production.catalog.delete"],
    ["POST /models/:id/image", "production.catalog.edit"],
    ["DELETE /models/:id/image", "production.catalog.edit"],
    ["POST /models/:id/test", ["production.catalog.view", "projects.items.manage"]],
    ["POST /models/:id/price", "sales.quotes.create"],
    ["POST /formulas/check", ["production.catalog.edit", "production.catalog.create"]],
    ["GET /articles", ["production.catalog.view", "production.config.view", "inventory.articles.view"]],
  ],
  productionOrders: [
    ["GET /board", "production.orders.view"],
    ["GET /", "production.orders.view"],
    ["GET /:id/pdf", "production.orders.print"],
    ["GET /:id", "production.orders.view"],
    ["POST /", "production.orders.create"],
    ["PATCH /:id", "production.orders.edit"],
    ["POST /:id/start", "production.orders.start"],
    ["POST /:id/consume", "production.orders.consume"],
    ["POST /:id/complete", "production.orders.complete"],
    ["POST /:id/cancel", "production.orders.cancel"],
  ],

  // ---------------------------------------------------------- Projects
  projects: [
    ["GET /planning", "projects.projects.view"],
    ["GET /people", ["projects.projects.view", "projects.tasks.manage"]],
    ["GET /", "projects.projects.view"],
    ["POST /", "projects.projects.create"],
    ["PUT /tasks/:taskId", "projects.tasks.manage"],
    ["DELETE /tasks/:taskId", "projects.tasks.manage"],
    ["DELETE /time/:entryId", "projects.time.manage"],
    ["GET /:id/production", "projects.projects.view"],
    ["POST /:id/production/plan", "projects.production.plan"],
    ["GET /:id", "projects.projects.view"],
    ["PUT /:id", "projects.projects.edit"],
    ["PATCH /:id/status", "projects.projects.status"],
    ["DELETE /:id/expenses/:expenseId", "projects.expenses.manage"],
    ["DELETE /:id/items/:itemId", "projects.items.manage"],
    ["DELETE /:id", "projects.projects.delete"],
    ["POST /:id/tasks", "projects.tasks.manage"],
    ["POST /:id/time", "projects.time.manage"],
    ["POST /:id/materials", "projects.materials.manage"],
    ["POST /:id/expenses", "projects.expenses.manage"],
    ["POST /:id/items", "projects.items.manage"],
    ["PUT /:id/items/:itemId", "projects.items.manage"],
  ],
  tracking: [
    ["GET /projects/:projectId", ["production.tracking.view", "logistics.tracking.view", "projects.projects.view"]],
    ["GET /projects", ["production.tracking.view", "logistics.tracking.view"]],
    ["POST /projects/:projectId/sync", ["production.tracking.update", "production.tracking.parts"]],
    ["POST /projects/:projectId/actions", ["production.tracking.update", "logistics.tracking.update"]], // which one: handler (the action)
    ["PUT /units/:unitId/parts", "production.tracking.parts"],
    ["POST /units/:unitId/cancel", "production.tracking.cancel"],
  ],

  // --------------------------------------------------------- Logistics
  logistics: [
    ["GET /to-deliver", "logistics.toDeliver.view"],
    ["GET /delivery-notes/:id/pdf", "logistics.notes.print"],
    ["GET /delivery-notes/:id", "logistics.notes.view"],
    ["GET /delivery-notes", "logistics.notes.view"],
    ["POST /delivery-notes/:id/status", ["logistics.notes.ship", "logistics.notes.deliver", "logistics.notes.cancel"]], // which one: handler
    ["POST /delivery-notes", "logistics.notes.create"],
    ["PUT /delivery-notes/:id", "logistics.notes.edit"],
    ["DELETE /delivery-notes/:id", "logistics.notes.delete"],
  ],
};

module.exports = { ROUTE_PERMISSIONS };
